# Generated by Django 5.0.1 on 2024-02-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('child', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
            ],
            options={
                'db_table': 'travel_book',
            },
        ),
        migrations.CreateModel(
            name='Travel_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'travel_register',
            },
        ),
    ]
