# Generated by Django 5.0.1 on 2024-03-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='destination_image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='travel_book',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='travel_book',
            name='child',
        ),
        migrations.AddField(
            model_name='travel_book',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='travel_book',
            name='num_travelers',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='travel_book',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travel_book',
            name='destination',
            field=models.CharField(choices=[('kerala', 'kerala'), ('tamil nadu', 'tamil nadu'), ('karnataka', 'karnataka'), ('up', 'up'), ('mp', 'mp'), ('delhi', 'delhi'), ('ap', 'ap')], default='delhi', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='travel_book',
            name='edate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='travel_book',
            name='location',
            field=models.CharField(choices=[('kerala', 'kerala'), ('tamil nadu', 'tamil nadu'), ('karnataka', 'karnataka'), ('up', 'up'), ('mp', 'mp'), ('delhi', 'delhi'), ('ap', 'ap')], default='kerala', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='travel_book',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='travel_book',
            name='sdate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
