# Generated by Django 5.0.1 on 2024-03-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_destination_remove_travel_book_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_book',
            name='sdate',
            field=models.DateField(null=True),
        ),
    ]
