# Generated by Django 5.0.1 on 2024-03-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_travel_book_sdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_book',
            name='num_travelers',
            field=models.IntegerField(null=True),
        ),
    ]
