# Generated by Django 5.0.1 on 2024-03-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_travel_book_your_date_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel_book',
            old_name='your_date_field',
            new_name='date',
        ),
    ]
