# Generated by Django 5.0.1 on 2024-03-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_rename_your_date_field_travel_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_book',
            name='date',
        ),
    ]
