# Generated by Django 5.0.1 on 2024-03-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_remove_travel_book_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='travel_reg',
            table='travel_reg',
        ),
    ]
